### ISSUE TITLE
Explore the options for viewing / configuring the storymap

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#10]
As preparation for presentation to stakeholders, we'll want to have a good idea of what is and is not possible. Working examples of variations will be better, but a description will be sufficient for now.

Examples/starters:
- [x]  can we scroll to zoom?
- [x] can we switch tiles?

**Comment by raghuarava2797** [comment]
can we scroll to zoom? - Yes, we can scroll to zoom (by enabling property to true: "scrollWheelZoom: true" inside L.map())
can we switch tiles? - Yes, we can add an option to switch the tiles for the story map.
