### ISSUE TITLE
Consolidate all CSS and JS into a single assets folder

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#11]
Eventually, all Leaflet-related assets will need to live in a single `assets` directory. This will avoid duplication and is necessary for the move into the WordPress plugin.

*newly added*

- [x] #21

**Comment by raghuarava2797** [comment]
Moved the CSS, JS and images to assets folder the commit related to this issue is:
https://github.com/NEU-DSG/Leaflet-core/commit/f2daef72c0ea7c35832e28cbf8ae8f897b378e40

**Comment by patrickmj** [comment]
it looks like there are a few places where this needs a final pass to cleanup. any CDNs should go in the appropriate place under assets, for example.

Make a task list of files to check in the comments here (or create a new issue for that).

**Comment by patrickmj** [comment]
- [ ] empty `res` folder and delete

**Comment by raghuarava2797** [comment]
All the files have been moved under assets folder:
https://github.com/NEU-DSG/Leaflet-core/commit/2fec34d8cb2d5a38b806ca4238358c9f20bcfc44

https://github.com/NEU-DSG/Leaflet-core/commit/06a29107670116fc7d755dc0bc1ce3f3a7277105
