### ISSUE TITLE
Create distinct .wp and .local extensions where needed

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#12]
For inclusion in the broader WordPress plugin, `.html` and some `.js` files will need to have distinct versions to make references to assets work correctly.

Compare the following from the Leaflet maps in the versions reconciled into WordPress:

```
            
            <script src="../wp-content/plugins/drs-tk/libraries/Ceres/assets/js/leaflet/brc/leaflet-brc-project.js"></script>
<!--
   
            <script src="../assets/js/leaflet/brc/leaflet-brc-project.js"></script>
            -->

```
Note the different paths to `assets`. Here, the commented out part is for `brc-leaflet.html.local`, and the uncommented part is for `brc-leaflet.html.wp`. It's easiest to track if the two files simply comment out what's not needed for the `.wp` vs `.local` versions without deleting the lines.

The same is true in the javascript files.

Similarly

- [x] #13

**Comment by raghuarava2797** [comment]
Created distinct .wp and .local extensions for JS and html files as required.
https://github.com/NEU-DSG/Leaflet-core/commit/2c75c8bfcd74dc9f4e6c476d3e6c7dac932c85e9

**Comment by patrickmj** [comment]
Looking through the .wp and .local files, I saw a few places where the paths to `assets` don't match up with the .wp and .local files

Make a task list here or as a new issue of files to double check, and check them off as you go through them.

**Comment by raghuarava2797** [comment]
Attached a comparison of the files from ceres (data/rendererTemplates/brc-leaflet.html.wp ) on left and (data/rendererTemplates/brc-leaflet.html.local) on right, I don't see any difference between those two incase of js script imports.


![image](https://github.com/NEU-DSG/Leaflet-core/assets/30839236/e02eceb2-e1c5-40e5-8124-90274d60177f)

**Comment by raghuarava2797** [comment]
I only see the difference for one of the JS script import and in case of images import.

![image](https://github.com/NEU-DSG/Leaflet-core/assets/30839236/cc2842c9-6075-49c2-8da0-72c359d82234)

**Comment by patrickmj** [comment]
Yep. The second screenshot shows exactly the kind of difference I'm talking about. Anything in the `<head>` tag you don't have to worry about -- those get taken care of when it gets integrated into the PHP of WordPress.

You'll see another difference of the same nature in https://github.com/NEU-DSG/Ceres/blob/develop/data/rendererTemplates/brc-leaflet.html.wp#L160 vs https://github.com/NEU-DSG/Ceres/blob/4101746a3eb23d05fdbfbcfa37485be3e0c45abf/data/rendererTemplates/brc-leaflet.html.local#L160

**Comment by raghuarava2797** [comment]
Updated the JS and html files of extension .local and .wp with correct file locations.

https://github.com/NEU-DSG/Leaflet-core/commit/0356e61382dda03833af6901ad0fd9b12235698c
