### ISSUE TITLE
js added to html should refer to a file in `assets`, wrapped in `jQuery()` so it only runs after page load

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#13]

**Comment by raghuarava2797** [comment]
Added jquery() to the js file, so it only runs after page load:

[]([Created distinct .wp and .local extensions for js and html files](https://github.com/NEU-DSG/Leaflet-core/commit/2c75c8bfcd74dc9f4e6c476d3e6c7dac932c85e9))
