### ISSUE TITLE
Bump Leaflet up to version 1.9.4

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#15]
The version we're on has [a bug in Safari](https://github.com/Leaflet/Leaflet/issues/7255). Fixed in later versions.

- [x] check that all the Leaflet plugins we use are compatible with the latest Leaflet, or version 1.8.0
- [x] make sure that the bump won't break backward compatibility with our work

If those are good, put it in and start testing.
Use a separate branch off of the one you are working in to test that everything works. I'll do some testing on that branch, too, then we'll create the PR.

**Comment by raghuarava2797** [comment]
Bumped up the version of the Leaflet JS to 1.9.4 (created a new branch called leaflet-version-bumpup-test)

https://github.com/NEU-DSG/Leaflet-core/commit/d78fcfc13b1429988a298ca96e3e39d2b522f69f

**Comment by raghuarava2797** [comment]
**check that all the Leaflet plugins we use are compatible with the latest Leaflet, or version 1.8.0** - yes other leaflet plugins are Compatible with leaflet version 1.9.4
wicket - 1.3.8 - Compatible
Jquery - 3.1.0 - Compatible

**make sure that the bump won't break backward compatibility with our work** - Testing the site thoroughly so the bump won't break backward compatibility with our work.
