### ISSUE TITLE
Tighten up the popup HTML creation

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#17]
Currently, there are many `if`s with nearly identical code.

Instead, as you loop through the bindings, have it call a single function that will take the given binding name and capitalize the first letter and add the colon.

This is part of a move toward generalizing how all of the popups are built for clarity and brevity.

**Comment by raghuarava2797** [comment]
Refactored the binding popup html code by replacing if cases with for loop.

https://github.com/NEU-DSG/Leaflet-core/commit/4372825bb0d82bfc9e0953b02b0e76a72a7a7e1a
