### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#18]
**Estimated time** < 2 hours

Go through the README and make sure that all the libraries and tiles listed are correct and still being used.

Also, give a brief (1 or 2 sentence) summary of what each library or tile set is used for. What would break if someone left it out?

**Comment by raghuarava2797** [comment]
Updated the README.md file.

https://github.com/NEU-DSG/Leaflet-core/commit/8d4dda65f35966a79ac16f0f3cfb6cd0826d691a
