### ISSUE TITLE
Get started with Leaflet Storymaps

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#2]
Starting with the [StoryMaps Leaflet Plugin](https://handsondataviz.org/leaflet-storymaps-with-google-sheets.html) recreate the example page in a standalone page, much as you did for maps

- [x] #8
- [x] #9

**Comment by raghuarava2797** [comment]
Create a story map example based on the some BRC SPARQL query data. (The code is in the csv-based-storymap branch).
