### ISSUE TITLE
empty res folder and delete

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#21]
Estimated time: < 2 hours

The `res` folder can be emptied as part of #11 . Under `assets`, in each directory create subdirectories as needed for `leaflet`, and move files to their appropriate place. Use more subdirectories and needed/logical. Thus you might end up with:

`assets` -> `images` -> `leaflet` -> `markers` as the new home for what's now `markers`.

**Comment by raghuarava2797** [comment]
The images, JS and CSS files under the res folder are not been used in the project, so remove them and freed up the res folder.

https://github.com/NEU-DSG/Leaflet-core/commit/2fec34d8cb2d5a38b806ca4238358c9f20bcfc44

**Comment by raghuarava2797** [comment]
Deleted the res folder and removed unused files.

https://github.com/NEU-DSG/Leaflet-core/commit/06a29107670116fc7d755dc0bc1ce3f3a7277105
