### ISSUE TITLE
Recreate the storymap using the raw result of the SPARQL query

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#22]
**Time estimate:**
< 3 hours

**Issue:**
We'll want to work directly with the results of the SPARQL query. I think you used something called `query.json` for just the map part. Use that again directly (not the `.csv`) to build the storymap.

- [x] switch from .csv to .json
- [x] adjust the js to produce to HTML

**Comment by raghuarava2797** [comment]
Added the API call to the SPARQL query to create the story map instead of getting the binding from csv file.

https://github.com/NEU-DSG/Leaflet-core/commit/16c87ea5511393f4157eb70e3ec4bb2c79d5497d
