### ISSUE TITLE
Check coordinate system from wiki data

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#24]
**Estimated Time** *the initial estimate of the time required to completion*
< 1 hour

**Description** *what the issue is about*

Digging through documentation for something else, I noticed that both wikidata and leaflet wants the get data in the WGS84 coordinate system format. But I think I remember that WKT is being used to parse location data. 

If that's true, we can remove that processing step. And create a new bigger issue to do that. 

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by patrickmj** [comment]
I stand corrected. Went back to my source about found the language to be confusing and I misread it. Nothing to do here.

**Comment by raghuarava2797** [comment]
FYI: I am currently using WKT to parse location.
So according to the description of the issue it is mentioned that I need to remove the WKT library, correct me if wrong?
When I get the data from SPARQL then location would be different format which I need to handle?
