### ISSUE TITLE
Create a way to hardcode a limited list of results for a storymap

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#25]
**Estimated Time** *the initial estimate of the time required to completion*
< 1 hour

**Description** *what the issue is about*
We'll need a way to limit the items that go on a storymap. This should be done after #22 so all the structures and code match.

Probably involves an array of items to include, but open to other solutions. Either way, the options for what to display should be stored _outside_ the main rendering steps.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
context menu click event on both cluster and individual marker to show Storymaps.

https://github.com/NEU-DSG/Leaflet-core/commit/f199f7ec2529e277799d0344d621127d62fe299d
