### ISSUE TITLE
Move from just the simple map to a storymap with a map click

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#26]
**Estimated Time** *the initial estimate of the time required to completion*
< 5 hours

**Description** *what the issue is about*
For navigation and exploration, user should be able to start on the basic map, right click on a location, see a popup that says "Go to storymap for this location" with the link, and be taken to a storymap of items with .25 miles of the clicked location.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
context menu click event on both cluster and individual marker to show Storymaps.

https://github.com/NEU-DSG/Leaflet-core/commit/f199f7ec2529e277799d0344d621127d62fe299d

**Comment by raghuarava2797** [comment]
Anywhere right click on map to 0.25 miles radius markers.

https://github.com/NEU-DSG/Leaflet-core/commit/f447727cea723687c77c08c9878a2360be05491a
