### ISSUE TITLE
Move from a marker cluster to a storymap of items within the cluster

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#27]
**Estimated Time** *the initial estimate of the time required to completion*
< 3 hours

**Description** *what the issue is about*
Building off of #26, right-click on a marker cluster and be taken to a storymap of the items within that cluster

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
context menu click event on both cluster and individual marker to show Storymaps.

https://github.com/NEU-DSG/Leaflet-core/commit/f199f7ec2529e277799d0344d621127d62fe299d
