### ISSUE TITLE
Create a single page with multiple storymaps

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#28]
**Estimated Time** *the initial estimate of the time required to completion*
< 6 hours

**Description** *what the issue is about*
We need  multiple sub-storymaps on a single single page. Tabs will let the user switch between between the sub-storymaps. The sub-storymaps will be page builder-defined named collections of URIs for the items. The interface will be built by the Beaver Builder team. For now, we will use a hard-coded named collection.

We should leave space in the data structure to allow for:
1. a description of the collection, along with its name
2. optional individual additional descriptions for each item. If a single item appears in multiple collection, the individual descriptions can/should be different

Those variations will be a distinct development step and feature request, but we should anticipate their future implementation.

This is a step toward a walking tour, in which someone with a hand-held device can select a tour of a small set of artworks and CERES will provide directions from one artwork to the next. 

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [x] a data structure to hold a title for a list of URIs that corresponds to storymap items that are part of the mini storymap
- [x] at least 2 such lists
- [x] tabs somewhere in the storymap page to select the item groups to display

**Comment by raghuarava2797** [comment]
Fixed: Create a single page with multiple Storymaps

https://github.com/NEU-DSG/Leaflet-core/commit/a6f963b3f60111281b0cc53ca26d862c3c5ccd39
