### ISSUE TITLE
Move hard-coded options to a distinct place

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#29]
**Estimated Time** *the initial estimate of the time required to completion*
< 2 hours

**Description** *what the issue is about*
There are many hard-code options for Leaflet, e.g., `defaultZoom`, but there are others that could make sense to move into a config options object in separate file.

A few for maps that I see. I suspect there are more.
- center
- scrollWheelZoom
- tiles
-

In that file, name the objects to distinguish between a map and a storymap

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [x] create a config object for maps
- [x] create a config object for storymaps
- [x] replaced the hardcoded text with config object properties.

**Comment by raghuarava2797** [comment]
Moved the hardcoded parts and constants to a saperate js file.

https://github.com/NEU-DSG/Leaflet-core/commit/cf141ed21ecd466b3365702410fc603b981e1273
