### ISSUE TITLE
Modularize code for storymaps and maps

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#30]
**Estimated Time** *the initial estimate of the time required to completion*
< 5 hours

**Description** *what the issue is about*
Common parts of maps and storymaps should be modularized, and the distinct parts should also have their own modulization.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [x] #31
- [x] #32
- [x] #33

**Comment by raghuarava2797** [comment]
Added css and js libraries to the project that are required for maps.

https://github.com/NEU-DSG/Leaflet-core/commit/2d0ce5aa1411370d46c064a714c8cbcd098a9097

**Comment by raghuarava2797** [comment]
Refactored the common code to one reusable js file
https://github.com/NEU-DSG/Leaflet-core/commit/946f96b31405f56ab80dd86f9ebe15636cc89261
