### ISSUE TITLE
move the common and distinct parts into their own reusable parts to import as needed

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#32]
< 4 hours

**Comment by raghuarava2797** [comment]
Replaced some of the static values in the leaflet-brc-project.js with config object.

https://github.com/NEU-DSG/Leaflet-core/commit/4500dbc64df8efdf3773f8f6d8d83f7113f46379

**Comment by raghuarava2797** [comment]
Refactored the common code to one reusable js file
https://github.com/NEU-DSG/Leaflet-core/commit/946f96b31405f56ab80dd86f9ebe15636cc89261
