### ISSUE TITLE
Build mechanism on map to switch tiles

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#34]
**Estimated Time** *the initial estimate of the time required to completion*
< 4 hours

**Description** *what the issue is about*
When on a map, I'd like to switch between tiles on the fly. Latest code in `csv-based-storymap` ( `4500dbc6` ) uses a different layer (which I like). For stakeholders, we'll want to show them switching back and forth from within the map. 

Will need a human-readable label for each one, and it looks like it might work as an on-the-fly switch of what's in `config.js`

**Links**
[Leaflet layers](https://leafletjs.com/examples/layers-control/)

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Tile layers switch between two different options
https://github.com/NEU-DSG/Leaflet-core/commit/b122fc28637268efc0395ff004f6bcc4fee17480
