### ISSUE TITLE
Links to `search-icon.svg` broken

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#35]
**Estimated Time** *the initial estimate of the time required to completion*
< 1 hour

**Description** *what the issue is about*
Just a broken link somewhere in the JS, so quick fix, but suggests additional issues of the distinction between `.local` and `.wp` files.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by patrickmj** [comment]
This might be a problem in my local machine -- I'll investigate there.

**Comment by raghuarava2797** [comment]
search-icon.svg link reference error fixed

https://github.com/NEU-DSG/Leaflet-core/commit/3f040a91cb0f5f26ea9c280704fa41dccdeaa09e

![image](https://github.com/NEU-DSG/Leaflet-core/assets/30839236/adbf572a-688d-4a12-9c0f-1878d93f5b16)
