### ISSUE TITLE
Broken reference in storymap

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#36]
**Estimated Time** *the initial estimate of the time required to completion*
< 1 hour

**Description** *what the issue is about*

```
Uncaught ReferenceError: statesData is not defined
    <anonymous> http://localhost/Leaflet-core/assets/js/leaflet/brc/leaflet-brc-project.js:25
leaflet-brc-project.js:25:1
```

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
https://github.com/NEU-DSG/Leaflet-core/commit/704ef197cbf52ed4f000256d4afbaebacc9f5bb1

![image](https://github.com/NEU-DSG/Leaflet-core/assets/30839236/77e02005-4017-4ea0-a39e-489cb726bc41)

**Comment by raghuarava2797** [comment]
Changed the reference of story map js file in storymap html

https://github.com/NEU-DSG/Leaflet-core/commit/1464994466c2971a0ec88828992dfe125743160c

![image](https://github.com/NEU-DSG/Leaflet-core/assets/30839236/27c1ca40-d374-45de-a317-5eaf901fafc2)
