### ISSUE TITLE
map search issue

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#37]
**Estimated Time** *the initial estimate of the time required to completion*
?
**Description** *what the issue is about*
via JF

This issue might be in the version that's merged into Ceres, and might be in the standalone, or both. We'll both therefore want to look at it as we get ready to merge everything together.

when I type a search term that is an exact match for one of the facets, the map immediately updates to show just the data points that match the term (e.g. “mural”, “acrylic”, etc.). Some of the results are puzzling; for instance, “statue” gets five hits although there are only three items with “statue” as their facet. 

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: The search option shows extra bindings than the searched text.
https://github.com/NEU-DSG/Leaflet-core/commit/90908af49af236273d8b197a9630bb62cb7b0a04
