### ISSUE TITLE
map search issue

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#38]
**Estimated Time** *the initial estimate of the time required to completion*

**Description** *what the issue is about*
via JF

This issue might be in the version that's merged into Ceres, and might be in the standalone, or both. We'll both therefore want to look at it as we get ready to merge everything together.

when I type a search term that is not an exact match for one of the facets, the map displays all items rather than no items. This includes search terms that are part of a facet (e.g. “boundary” or “environmental”, each of which are part of a phrase in the facets). It seems to me that if I search for a term that is not found, there should be some feedback indicating that there are no hits (e.g. “no items found” and all of the facets should be unchecked, and no items should show on the map).

when I search for a term from other metadata fields, such as the name of the item, the map successfully displays items that contain that string

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Added notification modal in case of no search result.
https://github.com/NEU-DSG/Leaflet-core/commit/57feac3c1b2f1de9e111390237324aff291bc435

**Comment by raghuarava2797** [comment]
![image](https://github.com/NEU-DSG/Leaflet-core/assets/30839236/daa47962-285c-4746-86e6-b6529adce260)
