### ISSUE TITLE
facets and search issue

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#39]
**Estimated Time** *the initial estimate of the time required to completion*
??

**Description** *what the issue is about*
via JF

This issue might be in the version that's merged into Ceres, and might be in the standalone, or both. We'll both therefore want to look at it as we get ready to merge everything together.

if I uncheck all of the facets and then do a search, I never get any search results (even searching for terms that are an exact match for facets terms, e.g. “mural”). My tentative expectations about the interaction/relationship between the search and the facets is that any search term should always take precedence, and the filters/facets should be a way to further narrow down the found set. If there’s no search term, that filtering starts from everything, but if there’s a search term, then the filtering/faceting starts from the baseline of the found set. So the filters should not have the capacity to (in effect) turn off the ability to search--I would expect the filters to reset when I do a new search, I think (and then I might reapply filters as needed to narrow down the new found set). However, we might need to take a look at other search interfaces/filtering interfaces and see how they handle this interaction, to understand the expected logic better.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: facets and search issue - facets should reset on search item.
https://github.com/NEU-DSG/Leaflet-core/commit/8b6bfaf0d696533219570d44300c87fe578800e7
