### ISSUE TITLE
facets pane placement

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#40]
**Estimated Time** *the initial estimate of the time required to completion*
??

**Description** *what the issue is about*
via JF

This issue might be in the version that's merged into Ceres, and might be in the standalone, or both. We'll both therefore want to look at it as we get ready to merge everything together.

the filters/facets pane comes out over the map and makes it so you can’t see much of the map; better to have that pane show up outside the frame of the map

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: issue with side panel overlaying on top of the leaflet map.
https://github.com/NEU-DSG/Leaflet-core/commit/768bebd83836f7c43a90f8a9557c05b9d24747c7

**Comment by raghuarava2797** [comment]
![image](https://github.com/NEU-DSG/Leaflet-core/assets/30839236/ab104da3-a256-40d6-9432-928001a8e33b)
