### ISSUE TITLE
recentering to story map looks wonky `Bounds not valid`

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#42]
**Estimated Time** *the initial estimate of the time required to completion*
< 2 hours
**Description** *what the issue is about*

When I move from the map to the storymap by cluster, the map doesn't get recentered onto Boston.
JS console shows an error of `Bounds not valid`

The map within the storymap should center on the boston area for the storymap

This appears to be erratic, and hard to duplicate

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: recentering to story map looks wonky Bounds not valid
https://github.com/NEU-DSG/Leaflet-core/commit/ff3c4fcf3a32d39c66ba9b13cb6b1538132ab68a
