### ISSUE TITLE
right clicking marker should give the same warning of what's going to happen: "Storymap of items in this group"

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#43]
**Estimated Time** *the initial estimate of the time required to completion*
< 3 hours

**Description** *what the issue is about*
There should be a popup that lets me know what'll happen next when I right-click on a marker cluster

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: right clicking marker should give the same warning of what's going to happen: "Storymap of items in this group"
https://github.com/NEU-DSG/Leaflet-core/commit/7f67cc51adea2efe77fa376cb29fff68aafb36fc
