### ISSUE TITLE
enter in search box should initiate the search

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#44]
**Estimated Time** *the initial estimate of the time required to completion*
< 1 hour

**Description** *what the issue is about*

When I type in a search term and then hit the `enter` button, that should launch the search. Basically hitting `enter` and clicking the `Go` button should have exactly the same effect.

While in there, the text should be "Search" instead of "Go" That's related to the accessibility work coming up.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: Enter in search box should initiate the search

https://github.com/NEU-DSG/Leaflet-core/commit/7a7ac6986ac6b391573240aa64bcb89f51d90402
