### ISSUE TITLE
We need a mechanism to reset the search/filtering results 

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#49]
**Estimated Time** *the initial estimate of the time required to completion*
<2 hours

**Description** *what the issue is about*
After a search happens, the only way to get back to the original state is to refresh the page.

We should have a reset button somewhere.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: We need a mechanism to reset the search/filtering results.
https://github.com/NEU-DSG/Leaflet-core/commit/01c00c42688e68c549e7018fb658bfc46cd261f2
