### ISSUE TITLE
missing image icon should be in config.js

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#50]
**Estimated Time** *the initial estimate of the time required to completion*
< 10 minutes

**Description** *what the issue is about*

It looks like the link to missing image icon hasn't been moved into the config file. It should be in the config.js file.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: missing image icon should be in config.js
https://github.com/NEU-DSG/Leaflet-core/commit/c7a00c4a69a2fdeec82ec54b2a88f50556bdc4bf
