### ISSUE TITLE
When searching, the map should resize to show all the results

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#51]
**Estimated Time** *the initial estimate of the time required to completion*
< 2 hours

**Description** *what the issue is about*
A followup from #48. If I have zoomed in to a map, then do a search, the map should resize and recenter to encompass all of the results

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: When searching, the map should resize to show all the results
https://github.com/NEU-DSG/Leaflet-core/commit/050b5bfd242b227b9ba946355054b1a7366d8626
