### ISSUE TITLE
In the storymap, the item receiving focus should also switch marker

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#52]
**Estimated Time** *the initial estimate of the time required to completion*
< 5 hours

**Description** *what the issue is about*

Currently, when scrolling down the items in a storymap, the map happily recenters on that item. However, when it happens to be very close to other items, it's hard to see which item is the focus.

To address this, a change of marker used will be helpful. Perhaps the icon turns to a red, rather than blue, marker. Or it could use a bigger marker when the item is the focus from the storymap scroll.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: In the storymap, the item receiving focus should also switch marker.
https://github.com/NEU-DSG/Leaflet-core/commit/fba3fae9a4a05b63822dea8c7e929294238cf458
