### ISSUE TITLE
Rework how the facets work

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#54]
**Estimated Time** < 5 hours

**Description** 
For the facets, the latest feedback indicates that the faceting should work somewhat differently.
- The checkboxes should be removed entirely
- Clicking a facet value should then filter to items with just that value
- The numbering should reflect the visible item count of the facet value across all the facets. Facet values with a count of 0 should not be displayed
- The reset button should be kept

I think the last two are essentially in place, except for hiding facet values with 0 hits, but worth double-checking and doing some extensive testing when a new version is up.

An example of the behavior they want is at https://catskillsinstitute.northeastern.edu/browse/ 
The list of currently active facet values that you see there can be left out for now.
The `Show More` button at the bottom of each list of facet values can also be left out -- the lists of values is short enough that I don't think it'll be needed, at least for now.

**Sub tasks** 
I think it'll be prudent to keep a distinct branch that maintains the current behavior of displaying all the facets, even when the count is zero, just in case stakeholders change their minds after seeing the new version.

**Comment by raghuarava2797** [comment]
Fixed: Rework how the facets work
https://github.com/NEU-DSG/Leaflet-core/commit/34bf7b36ca521a640c358eed3a114815e781fde2
