### ISSUE TITLE
Remove the radius filter

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#55]
**Estimated Time** < 1hr

**Description** 

The filter/search by radius got confusing to some testers, since they couldn't immediately see what the center of the radius is. Better to leave that out entirely.

**Sub tasks** *briefly and descriptively add sub tasks, which may be converted to issues*
- [ ]

**Comment by raghuarava2797** [comment]
Fixed: Remove the radius filter.
https://github.com/NEU-DSG/Leaflet-core/commit/752b2439f741dabbcc66d628af147dc4f314882a
