### ISSUE TITLE
make up some mock CSV data that is Boston-based

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/Leaflet-core#9]
To make the data more familiar, add some additional Boston-specific items. It's fine to hand-convert some of the items into CSV from the SPARQL query results. We'll want to start with just a handful to give the idea, not a full conversion for all the items.

**Comment by raghuarava2797** [comment]
Create a story map example based on the some BRC SPARQL query data. (The code is in the csv-based-storymap branch).
